install: ./mvnw -U install --quiet -DskipTests=true -P bootstrap
jdk:
- oraclejdk8
language: java
script:
- touch /tmp/NOW
- echo GIBSTUDYSTART $(date)
- jdk_switcher use oraclejdk7
- ./mvnw clean test -P bootstrap
- jdk_switcher use oraclejdk8
- ./mvnw -U clean test -P spring5
- echo GIBSTUDYEND $(date)
- cd $TRAVIS_BUILD_DIR
- echo TESTNUM $(find . -name TEST-*.xml -newer /tmp/NOW | wc -l)
services:
- redis-server
